name: Upload Weights
on:
  push:
    tags:
      - "v*"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload weights
        uses: softprops/action-gh-release@v2
        with:
          files: ./weights/*.h5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
